# projects.toml file describing inputs for dream2nix
#
# To re-generate this file, run:
#   nix run .#detect-projects $source
# ... where `$source` points to the source of your project.
#
# If the local flake is unavailable, alternatively execute the app from the
# upstream dream2nix flake:
#   nix run github:nix-community/dream2nix#detect-projects $source

[""]
name = ""
relPath = ""
subsystem = "nodejs"
translator = "yarn-lock"
translators = [ "yarn-lock", "package-json",]

[chopsticks-executor]
name = "chopsticks-executor"
relPath = "executor"
subsystem = "rust"
translator = "cargo-lock"
translators = [ "cargo-lock", "cargo-toml",]

["".subsystemInfo]
workspaces = [ "packages/chopsticks"]

[chopsticks-executor.subsystemInfo]
workspaceMembers = []
[[chopsticks-executor.subsystemInfo.crates]]
name = "chopsticks-executor"
relPath = "executor"
version = "0.4.2"
